#!/bin/sh
# Autor: Wellington 
# Dep: Infra T.I 
# cargo: Analista de Sistema  
# Site: https://www.irmaosgoncalves.com.br 
# Facebook: https://www.facebook.com/supermercadoig 
# YouTube: https://www.youtube.com/@supermercadoig 
# Instagram: https://www.instagram.com/irmaosgoncalves 
# Data de criação: 15/12/2023 
# Data de atualização: 16/12/2023 
# Versão: 0.1 
# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64x
# Testado e homologado para a versão do Vsftpd Server v3.0.x

echo "Esta conta é limitada apenas para acesso remoto ao Servidor FTP."